version: '3.7'
services:
  trivio_backend:
    build:
      context: .
      dockerfile: ./docker/trivio_backend/Dockerfile
    volumes:
    #  - ./trivio_backend:/trivio_backend
      - ./var/log/gunicorn:/var/log/gunicorn
      - ./var/db:/var/db
    command: ['./manage.py', 'runserver', '0.0.0.0:8000']
    ports:
      - "8000:8000"
